imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true


doctrine:
    dbal:
        driver:   pdo_mysql
        host:     127.0.0.1
        port:     ~
        dbname:   symfex_test
        user:     root
        password: admin
        charset:  UTF8

        #driver:   pdo_sqlite
        ##memory: true
        #path: %kernel.cache_dir%/test.db
