fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /user

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

app_app:
    resource: "@AppAppBundle/Resources/config/routing.yml"
    prefix:   /

bones_core:
    resource: "@BonesCoreBundle/Resources/config/routing.yml"
    prefix:   /bones

