fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_app:
    resource: "@AppAppBundle/Resources/config/routing.yml"
    prefix:   /

bones_core:
    resource: "@BonesCoreBundle/Resources/config/routing.yml"
    prefix:   /bones

