bones_store:
    resource: "@BonesStoreBundle/Resources/config/routing.yml"
    prefix:   /store

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /user

app_app:
    resource: "@AppAppBundle/Resources/config/routing.yml"
    prefix:   /

bones_core:
    resource: "@BonesCoreBundle/Resources/config/routing.yml"
    prefix:   /bones

