app_default:
    path:     /
    defaults: { _controller: AppAppBundle:Default:index}

app_create:
    path: /create
    defaults: { _controller: AppAppBundle:Default:create}

app_show:
    path: /show
    defaults: { _controller: AppAppBundle:Default:show}
