app_default:
    path:     /
    defaults: { _controller: AppAppBundle:Default:index}

login_index:
    path:     /login
    defaults: { _controller: AppAppBundle:Login:index }

login_process:
    path:     /process
    defaults: { _controller: AppAppBundle:Login:process }
