band:
    path:     /band/lazy
    defaults: { _controller: DiscographyBundle:Band:indexLazy }

band/eager:
    path:     /band/eager
    defaults: { _controller: DiscographyBundle:Band:indexEager }


band/avid:
    path:     /band/avid
    defaults: { _controller: DiscographyBundle:Band:indexAvid }
