<?php

namespace DiscographyBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Query\Expr\Join;

/**
 * BandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAllWithMembers()
    {
//        $qb = $this->getEntityManager()->createQueryBuilder();
//        $qb->select('b', 'm')
//            ->from("DiscographyBundle:Band", 'b')
//            ->join("DiscographyBundle:Musician", 'm', Join::WITH);
        $qb = $this
            ->getEntityManager()
            ->createQuery('select b from DiscographyBundle\Entity\Band b');

        return $qb
            ->setFetchMode('DiscographyBundle\Entity\Band', 'members', ClassMetadata::FETCH_EAGER)
            ->execute();

    }
}
